/**
 * Formats generated TypeScript code for model interfaces.
 * 
 * Handles:
 * - Generating model interface definitions
 * - Creating method signature documentation
 * - Formatting with proper indentation and JSDoc
 * - Generating index file with all exports
 */

import { ModelMetadata } from '../introspection/types';
import { getFieldTypeExpression, generateFieldJSDoc, isWritableField } from './type-mappers';

/**
 * Converts a model name like 'res.partner' to TypeScript interface name 'ResPartner'.
 * 
 * Logic:
 * 1. Split on '.'
 * 2. Remove common prefixes (res, sale, project, etc. at first segment only)
 * 3. Join segments
 * 4. CamelCase each segment
 * 5. Capitalize first letter
 * 
 * Examples:
 * - res.partner → ResPartner
 * - sale.order → SaleOrder
 * - project.project → ProjectProject
 * - account.move → AccountMove
 * 
 * @param modelName - Odoo model name (e.g., 'res.partner')
 * @returns TypeScript interface name (e.g., 'ResPartner')
 */
export function modelNameToInterfaceName(modelName: string): string {
  const parts = modelName.split('.');
  
  // Capitalize each part: 'res' -> 'Res', 'partner' -> 'Partner'
  const capitalized = parts.map(part => {
    return part.charAt(0).toUpperCase() + part.slice(1);
  });

  return capitalized.join('');
}

/**
 * Generates a TypeScript interface definition for a model.
 * 
 * Produces:
 * - Interface declaration with all fields
 * - JSDoc comments on fields with descriptions
 * - Proper handling of optional vs required fields
 * - Method signatures as JSDoc comments
 * 
 * @param metadata - Complete model metadata (model + fields)
 * @returns Formatted TypeScript interface code
 */
export function generateModelInterface(metadata: ModelMetadata): string {
  const interfaceName = modelNameToInterfaceName(metadata.model.model);
  const lines: string[] = [];

  // Add model documentation header
  lines.push('/**');
  lines.push(` * ${metadata.model.name}`);
  if (metadata.model.info) {
    const info = metadata.model.info
      .split('\n')
      .map(line => line.trim())
      .filter(line => line.length > 0)
      .join(' ');
    if (info) {
      lines.push(` * `);
      lines.push(` * ${info}`);
    }
  }
  lines.push(` * `);
  lines.push(` * Odoo Model: ${metadata.model.model}`);
  lines.push(' */');

  // Interface declaration
  lines.push(`export interface ${interfaceName} {`);

  // Add fields
  for (const field of metadata.fields) {
    // Add JSDoc for field
    const jsDoc = generateFieldJSDoc(field);
    const jsDocLines = jsDoc.split('\n');
    for (const line of jsDocLines) {
      lines.push('  ' + line);
    }

    // Add field definition
    const optional = !field.required ? '?' : '';
    const typeExpr = getFieldTypeExpression(field);
    lines.push(`  ${field.name}${optional}: ${typeExpr};`);
    lines.push('');
  }

  // Add method signatures as JSDoc comments
  lines.push('  /**');
  lines.push('   * Search for records matching a domain.');
  lines.push('   */');
  lines.push(`  // search(domain: any[]): Promise<number[]>;`);
  lines.push('');

  lines.push('  /**');
  lines.push('   * Read specified fields from records.');
  lines.push('   */');
  lines.push(`  // read(ids: number[], fields?: string[]): Promise<${interfaceName}[]>;`);
  lines.push('');

  const writableFields = metadata.fields.filter(isWritableField);
  writableFields.map(f => f.name).join(' | ');
  
  lines.push('  /**');
  lines.push('   * Create a new record with the given values.');
  lines.push('   */');
  lines.push(`  // create(values: Partial<${interfaceName}>): Promise<number>;`);
  lines.push('');

  lines.push('  /**');
  lines.push('   * Update records with new values.');
  lines.push('   */');
  lines.push(`  // write(ids: number[], values: Partial<${interfaceName}>): Promise<boolean>;`);
  lines.push('');

  lines.push('  /**');
  lines.push('   * Delete records by ID.');
  lines.push('   */');
  lines.push(`  // unlink(ids: number[]): Promise<boolean>;`);
  lines.push('');

  lines.push('}');

  return lines.join('\n');
}

/**
 * Generates the complete generated.ts file with all model interfaces and exports.
 * 
 * Includes:
 * - File header with generation notice
 * - All model interfaces
 * - Index exports
 * 
 * @param allMetadata - Array of all model metadata
 * @returns Complete file content for src/models/generated.ts
 */
export function generateCompleteFile(allMetadata: ModelMetadata[]): string {
  const lines: string[] = [];

  // File header
  lines.push('/**');
  lines.push(' * Auto-generated TypeScript interfaces for Odoo models.');
  lines.push(' * ');
  lines.push(' * This file is generated by @odoo-client/codegen from live Odoo metadata.');
  lines.push(' * DO NOT edit manually - regenerate using: npm run generate');
  lines.push(' * ');
  lines.push(' * Generated interfaces include:');
  lines.push(' * - All model fields with correct types');
  lines.push(' * - Required vs optional field markers');
  lines.push(' * - JSDoc comments from Odoo help text');
  lines.push(' * - Method signature documentation');
  lines.push(' */');
  lines.push('');

  // Generate each model interface
  for (const metadata of allMetadata) {
    lines.push(generateModelInterface(metadata));
    lines.push('');
    lines.push('');
  }

  // Generate index exports
  lines.push('// Type exports');
  for (const metadata of allMetadata) {
    const interfaceName = modelNameToInterfaceName(metadata.model.model);
    lines.push(`export type { ${interfaceName} };`);
  }

  return lines.join('\n');
}

/**
 * Generates helper type definitions for common patterns.
 * 
 * Includes:
 * - SearchOptions type
 * - ReadOptions type
 * - CreateOptions type
 * - WriteOptions type
 * 
 * @returns TypeScript code defining helper types
 */
export function generateHelperTypes(): string {
  return `/**
 * Options for search operations.
 */
export interface SearchOptions {
  domain?: any[];
  order?: string;
  limit?: number;
  offset?: number;
}

/**
 * Options for read operations.
 */
export interface ReadOptions {
  fields?: string[];
  context?: Record<string, any>;
}

/**
 * Options for search+read combined operations.
 */
export interface SearchReadOptions extends SearchOptions, ReadOptions {}

/**
 * Options for create operations.
 */
export interface CreateOptions {
  context?: Record<string, any>;
}

/**
 * Options for write operations.
 */
export interface WriteOptions {
  context?: Record<string, any>;
}

/**
 * Options for unlink (delete) operations.
 */
export interface UnlinkOptions {
  context?: Record<string, any>;
}
`;
}
