import * as fs from 'fs';
import * as path from 'path';
import { MarkdownGenerator, GeneratorOptions } from './markdown-generator';
import { skillRegistry } from '../registry';
import { SkillDefinition } from '../types';

/**
 * Generate Markdown file for a single SKILL
 */
export function generateSkill(
  skill: SkillDefinition,
  options?: Partial<GeneratorOptions>
): string {
  const generator = new MarkdownGenerator(options);
  return generator.generate(skill);
}

/**
 * Generate all SKILL Markdown files to a directory
 */
export async function generateAllSkills(
  outputDir: string,
  options?: Partial<GeneratorOptions>
): Promise<{ generated: string[]; errors: Array<{ id: string; error: Error }> }> {
  const generator = new MarkdownGenerator(options);
  const generated: string[] = [];
  const errors: Array<{ id: string; error: Error }> = [];

  // Ensure output directory exists
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  for (const skill of skillRegistry.skills) {
    try {
      const markdown = generator.generate(skill);
      const filename = `${skill.id}.md`;
      const filepath = path.join(outputDir, filename);

      fs.writeFileSync(filepath, markdown, 'utf-8');
      generated.push(filepath);
    } catch (error) {
      errors.push({
        id: skill.id,
        error: error instanceof Error ? error : new Error(String(error)),
      });
    }
  }

  return { generated, errors };
}

/**
 * Generate a summary index of all SKILLs
 */
export function generateIndex(): string {
  const lines = [
    '# Odoo Toolbox SKILLs',
    '',
    'Available Claude Code commands for interacting with Odoo.',
    '',
    '> **Nota**: Estos comandos han sido generados y validados contra una instancia',
    '> de Odoo 17 Community de prueba (Docker). Los ejemplos funcionan con una base',
    '> de datos limpia. Tu instancia puede tener módulos adicionales, campos custom,',
    '> o configuraciones diferentes que requieran adaptación.',
    '',
  ];

  // Group by level
  const levels = ['elementary', 'user', 'admin'] as const;

  for (const level of levels) {
    const skills = skillRegistry.getByLevel(level);

    if (skills.length === 0) continue;

    const levelTitle =
      level === 'elementary'
        ? 'Elementary (Getting Started)'
        : level === 'user'
          ? 'User (Business Operations)'
          : 'Admin (Configuration)';

    lines.push(`## ${levelTitle}`);
    lines.push('');
    lines.push('| Command | Description |');
    lines.push('|---------|-------------|');

    for (const skill of skills) {
      lines.push(`| [\`/${skill.id}\`](./${skill.id}.md) | ${skill.summary} |`);
    }

    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by @odoo-toolbox/skills*');

  return lines.join('\n');
}
