import { SkillDefinition, SkillParameter } from '../types';

export interface GeneratorOptions {
  /** Include tested badge for examples */
  showTestedBadge: boolean;
}

const defaultOptions: GeneratorOptions = {
  showTestedBadge: true,
};

/**
 * Generates Claude Code command Markdown from SKILL definitions
 */
export class MarkdownGenerator {
  private options: GeneratorOptions;

  constructor(options: Partial<GeneratorOptions> = {}) {
    this.options = { ...defaultOptions, ...options };
  }

  /**
   * Generate complete Markdown for a SKILL
   */
  generate(skill: SkillDefinition): string {
    const sections = [
      this.generateHeader(skill),
      this.generateLevelSection(skill),
      this.generatePrerequisites(skill),
      this.generateParametersTable(skill),
      this.generateUsageSection(skill),
      this.generateKeyConceptsSection(skill),
      this.generateRelatedSection(skill),
      this.generateReferencesSection(skill),
      this.generateFooter(),
    ];

    return sections.filter(Boolean).join('\n\n');
  }

  private generateHeader(skill: SkillDefinition): string {
    return `# /${skill.id}\n\n${skill.summary}`;
  }

  private generateLevelSection(skill: SkillDefinition): string {
    const levelDescriptions: Record<string, string> = {
      elementary: 'Basic operations - getting started',
      user: 'Standard business operations',
      admin: 'Administrative and configuration tasks',
    };

    const level = this.capitalize(skill.level);
    const description = levelDescriptions[skill.level] || '';

    return `## Level\n\n**${level}** - ${description}`;
  }

  private generatePrerequisites(skill: SkillDefinition): string {
    const lines = ['## Prerequisites'];

    if (skill.moduleDependencies.length > 0) {
      const required = skill.moduleDependencies.filter((m) => m.required);
      const optional = skill.moduleDependencies.filter((m) => !m.required);

      if (required.length > 0) {
        const modules = required.map((m) => `**${m.displayName}**`).join(', ');
        lines.push(`- Modules (required): ${modules}`);
      }
      if (optional.length > 0) {
        const modules = optional.map((m) => m.displayName).join(', ');
        lines.push(`- Modules (optional): ${modules}`);
      }
    }

    lines.push('- Authenticated OdooClient connection');

    return lines.join('\n');
  }

  private generateParametersTable(skill: SkillDefinition): string {
    if (skill.parameters.length === 0) {
      return '## Parameters\n\nThis SKILL has no configurable parameters.';
    }

    const header = '| Parameter | Type | Required | Description |';
    const separator = '|-----------|------|----------|-------------|';
    const rows = skill.parameters.map((p) => this.formatParameterRow(p));

    return `## Parameters\n\n${[header, separator, ...rows].join('\n')}`;
  }

  private formatParameterRow(param: SkillParameter): string {
    const required = param.required ? 'Yes' : 'No';
    let desc = param.description;

    if (param.default !== undefined) {
      desc += ` (default: \`${JSON.stringify(param.default)}\`)`;
    }

    return `| \`${param.name}\` | ${param.type} | ${required} | ${desc} |`;
  }

  private generateUsageSection(skill: SkillDefinition): string {
    const lines = ['## Usage'];

    for (const example of skill.examples) {
      lines.push('');
      lines.push(`### ${example.title}`);

      if (this.options.showTestedBadge && example.tested) {
        lines.push('');
        lines.push('*✓ This example is tested against a live Odoo instance*');
      }

      lines.push('');
      lines.push(example.description);
      lines.push('');
      lines.push('```typescript');
      lines.push(example.code);
      lines.push('```');
    }

    return lines.join('\n');
  }

  private generateKeyConceptsSection(skill: SkillDefinition): string {
    if (!skill.description) return '';

    return `## Key Concepts\n\n${skill.description}`;
  }

  private generateRelatedSection(skill: SkillDefinition): string {
    if (skill.relatedSkills.length === 0) return '';

    const links = skill.relatedSkills.map((s) => `- \`/${s}\``);
    return `## Related SKILLs\n\n${links.join('\n')}`;
  }

  private generateReferencesSection(skill: SkillDefinition): string {
    if (skill.odooReferences.length === 0) return '';

    const links = skill.odooReferences.map((url) => {
      const filename = url.split('/').pop() || url;
      return `- [${filename}](${url})`;
    });

    return `## Odoo Source References\n\n${links.join('\n')}`;
  }

  private generateFooter(): string {
    return `---\n\n*Generated by @odoo-toolbox/skills*`;
  }

  private capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }
}
